# Accessing Data within Pandas - Lab

## Introduction

In this lab, we'll look at a data set which contains information World cup matches. Let's use the pandas commands learned in the previous lecture to learn more about our data!

## Objectives
You will be able to:
* Understand and explain some key Pandas methods
* Access DataFrame data by using the label
* Perform boolean indexing on both Series and DataFrames
* Use simple selectors for series
* Set new Series and DataFrame inputs

## Load the data

Load the file `WorldCupMatches.csv` as a dataframe in Pandas

In [1]:
import pandas as pd
df = pd.read_csv('WorldCupMatches.csv')
df.head()

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,4444.0,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX
1,1930,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3,0,Belgium,,18346.0,2,0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201,1090,USA,BEL
2,1930,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059.0,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549.0,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409.0,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA

## Common methods and attributes

Use the correct method to look at the first 7 rows of the data set.

In [2]:
df.head(7)

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,4444.0,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX
1,1930,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3,0,Belgium,,18346.0,2,0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201,1090,USA,BEL
2,1930,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059.0,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549.0,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409.0,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA
5,1930,16 Jul 1930 - 14:45,Group 1,Parque Central,Montevideo,Chile,3,0,Mexico,,9249.0,1,0,CRISTOPHE Henry (BEL),APHESTEGUY Martin (URU),LANGENUS Jean (BEL),201,1095,CHI,MEX
6,1930,17 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,4,0,Bolivia,,18306.0,0,0,MATEUCCI Francisco (URU),LOMBARDI Domingo (URU),WARNKEN Alberto (CHI),201,1092,YUG,BOL

Look at the last 3 rows of the data set.

In [3]:
df.tail(3)

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
849,2014,09 Jul 2014 - 17:00,Semi-finals,Arena de Sao Paulo,Sao Paulo,Netherlands,0,0,Argentina,Argentina win on penalties (2 - 4),63267.0,0,0,C�neyt �AKIR (TUR),DURAN Bahattin (TUR),ONGUN Tarik (TUR),255955,300186490,NED,ARG
850,2014,12 Jul 2014 - 17:00,Play-off for third place,Estadio Nacional,Brasilia,Brazil,0,3,Netherlands,,68034.0,0,2,HAIMOUDI Djamel (ALG),ACHIK Redouane (MAR),ETCHIALI Abdelhak (ALG),255957,300186502,BRA,NED
851,2014,13 Jul 2014 - 16:00,Final,Estadio do Maracana,Rio De Janeiro,Germany,1,0,Argentina,Germany win after extra time,74738.0,0,0,Nicola RIZZOLI (ITA),Renato FAVERANI (ITA),Andrea STEFANI (ITA),255959,300186501,GER,ARG

Get a concise summary of your data using `.info()`

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 852 entries, 0 to 851
Data columns (total 20 columns):
Year                    852 non-null int64
Datetime                852 non-null object
Stage                   852 non-null object
Stadium                 852 non-null object
City                    852 non-null object
Home Team Name          852 non-null object
Home Team Goals         852 non-null int64
Away Team Goals         852 non-null int64
Away Team Name          852 non-null object
Win conditions          852 non-null object
Attendance              850 non-null float64
Half-time Home Goals    852 non-null int64
Half-time Away Goals    852 non-null int64
Referee                 852 non-null object
Assistant 1             852 non-null object
Assistant 2             852 non-null object
RoundID                 852 non-null int64
MatchID                 852 non-null int64
Home Team Initials      852 non-null object
Away Team Initials      852 non-null object
dtypes: float64(1), int64(7), object(12)
memory usage: 133.2+ KB

Obtain a tuple representing the number of rows and number of columns

In [5]:
df.shape

(852, 20)

Use the appropriate attribute to get the column names

In [6]:
df.columns

Index(['Year', 'Datetime', 'Stage', 'Stadium', 'City', 'Home Team Name',
       'Home Team Goals', 'Away Team Goals', 'Away Team Name',
       'Win conditions', 'Attendance', 'Half-time Home Goals',
       'Half-time Away Goals', 'Referee', 'Assistant 1', 'Assistant 2',
       'RoundID', 'MatchID', 'Home Team Initials', 'Away Team Initials'],
      dtype='object')

## Selecting dataframe information

When looking at the dataframe's `.head()`, you might have noticed that the games are structured chronologically in the dataframe.

Use the right selection method to print all the information from the 3rd to the 5th game.

In [7]:
df.iloc[3:6]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549.0,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409.0,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA
5,1930,16 Jul 1930 - 14:45,Group 1,Parque Central,Montevideo,Chile,3,0,Mexico,,9249.0,1,0,CRISTOPHE Henry (BEL),APHESTEGUY Martin (URU),LANGENUS Jean (BEL),201,1095,CHI,MEX

Now, print all the info from game 5-9, but we're only interested to print out the "Home Team Name" and the "Away Team Name",

In [8]:
df.loc[5:9,['Home Team Name', 'Away Team Name']]

  Home Team Name Away Team Name
5          Chile         Mexico
6     Yugoslavia        Bolivia
7            USA       Paraguay
8        Uruguay           Peru
9          Chile         France

Next, we'd like the information on all the games played in Group 3 for the 1950 World Cup.

In [9]:
df.loc[(df['Year'] == 1950 )& (df['Stage'] == 'Group 3')]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
56,1950,25 Jun 1950 - 15:00,Group 3,Pacaembu,Sao Paulo,Sweden,3,2,Italy,,36502.0,2,1,LUTZ Jean (SUI),BERANEK Alois (AUT),TEJADA Carlos (MEX),208,1219,SWE,ITA
61,1950,29 Jun 1950 - 15:30,Group 3,Durival de Brito,Curitiba,Sweden,2,2,Paraguay,,7903.0,2,1,MITCHELL Robert (SCO),LEMESIC Leo (YUG),GARCIA Prudencio (USA),208,1228,SWE,PAR
65,1950,02 Jul 1950 - 15:00,Group 3,Pacaembu,Sao Paulo,Italy,2,0,Paraguay,,25811.0,1,0,ELLIS Arthur (ENG),GARCIA Prudencio (USA),DE LA SALLE Charles (FRA),208,1218,ITA,PAR

Let's repeat the command above, but now we only want to print out the attendance column for the Group 3 games

You can combine conditions like this:

`df[(condition1) | (condition2)]`  -> Returns rows where either condition is true

`df[(condition1) & (condition2)]`  -> Returns rows where both conditions are true

In [10]:
df.loc[(df['Year'] == 1950 )& (df['Stage'] == 'Group 3'), 'Attendance']

56    36502.0
61     7903.0
65    25811.0
Name: Attendance, dtype: float64

Throughout the entire history of the world cup, How many Home games were played by the Netherlands?

In [11]:
df.loc[(df['Home Team Name'] == 'Netherlands')].shape #32 games

(32, 20)

How many games were played by the Netherlands in total?

In [12]:
df.loc[(df['Home Team Name'] == 'Netherlands') | (df['Away Team Name'] == 'Netherlands')].shape #54 games

(54, 20)

Next, let's try and figure out how many games the USA played in the 2014 world cup.

In [13]:
df.loc[(df['Year'] == 2014) & ((df['Home Team Name'] == 'USA') | (df['Away Team Name'] == 'USA'))].shape #5 games

(5, 20)

Now, let's try to find out how many countries participated in the 1986 world cup.

Hint 1: as a first step, create a new data set that only contain games in that year.

Hint 2: You can use `.unique()` to make sure you don't end up with duplicate country names.

In [14]:
df_1986 = df.loc[df['Year'] == 1986]
df_1986.head()

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
360,1986,31 May 1986 - 12:00,Group A,Estadio Azteca,Mexico City,Bulgaria,1,1,Italy,,96000.0,0,1,FREDRIKSSON Erik (SWE),CODESAL MENDEZ Edgardo (MEX),ROTH Volker (GER),308,459,BUL,ITA
361,1986,01 Jun 1986 - 16:00,Group C,Nou Camp - Estadio Le�n,Leon,Canada,0,1,France,,65500.0,0,0,SILVA ARCE Hernan (CHI),MENDEZ MOLINA Romulo (GUA),ULLOA MORERA Berny (CRC),308,468,CAN,FRA
362,1986,01 Jun 1986 - 12:00,Group D,Jalisco,Guadalajara,Spain,0,1,Brazil,,35748.0,0,0,BAMBRIDGE Christopher (AUS),SOCHA David (USA),KEIZER Jan (NED),308,439,ESP,BRA
363,1986,02 Jun 1986 - 12:00,Group C,Estadio Irapuato,Irapuato,Soviet Union,6,0,Hungary,,16500.0,3,0,AGNOLIN Luigi (ITA),COURTNEY George (ENG),BRUMMEIER Horst (AUT),308,610,URS,HUN
364,1986,02 Jun 1986 - 12:00,Group A,Estadio Ol�mpico Universitario,Mexico City,Argentina,3,1,Korea Republic,,60000.0,2,0,SANCHEZ ARMINIO Victoriano (ESP),GONZALEZ ROA Gabriel (PAR),DIAZ PALACIO Jesus (COL),308,395,ARG,KOR

In [15]:
home = list(df_1986['Home Team Name'].unique())
away = list(df_1986['Away Team Name'].unique())
len(home) + len(away)

48

In the world cup history, how matches had more than 5 goals in total?

In [16]:
df['Total Goals'] = df['Home Team Goals'] + df['Away Team Goals']
len(df[df['Total Goals'] >= 5])

147

## Changing values and creating new columns

With the information you currently have in your `df`, create a new column "Half-time Goals".

In [17]:
df['Half-time Goals'] = df['Half-time Home Goals'] + df['Half-time Away Goals']

Run the code below. You'll notice that for Korea, there are records for both North-Korea (Korea DPR) and South-Korea (Korea Republic).

In [18]:
df.loc[df["Home Team Name"].str.contains('Korea'), "Home Team Name" ]

179         Korea DPR
187         Korea DPR
374    Korea Republic
386    Korea Republic
434    Korea Republic
444    Korea Republic
480    Korea Republic
524    Korea Republic
593    Korea Republic
609    Korea Republic
635    Korea Republic
642    Korea Republic
655    Korea Republic
710    Korea Republic
753         Korea DPR
802    Korea Republic
818    Korea Republic
Name: Home Team Name, dtype: object

Imagine that for some reason, we simply want Korea listed as one entry, so we want to replace every "Home Team Name" and "Away Team Name" entry that contains "Korea" to simply "Korea". In the same way, we want to change the columns "Home Team Initials" and "Away Team Initials" to NSK (North & South Korea) instead of "KOR" and "PRK".

In [19]:
df.loc[df["Home Team Name"].str.contains('Korea'), "Home Team Name" ] = 'Korea'
df.loc[df["Away Team Name"].str.contains('Korea'), "Away Team Name" ] = 'Korea'

In [20]:
df.loc[df["Home Team Initials"] == 'KOR', "Home Team Initials" ] = 'NSK'
df.loc[df["Away Team Initials"] == 'KOR', "Away Team Initials" ] = 'NSK'
df.loc[df["Home Team Initials"] == 'PRK', "Home Team Initials" ] = 'NSK'
df.loc[df["Away Team Initials"] == 'PRK', "Away Team Initials" ] = 'NSK'

Make sure to verify your answer!

In [21]:
df.loc[df["Home Team Name"].str.contains('Korea')]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,...,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials,Total Goals,Half-time Goals
179,1966,15 Jul 1966 - 19:30,Group 4,Ayresome Park,Middlesbrough,Korea,1,1,Chile,,...,1,KANDIL Aly Hussein (EGY),CRAWFORD William (SCO),FINNEY Jim (ENG),238,1609,NSK,CHI,2,1
187,1966,19 Jul 1966 - 19:30,Group 4,Ayresome Park,Middlesbrough,Korea,1,0,Italy,,...,0,SCHWINTE Pierre (FRA),ADAIR John (NIR),TAYLOR John (ENG),238,1679,NSK,ITA,1,1
374,1986,05 Jun 1986 - 16:00,Group A,Estadio Ol�mpico Universitario,Mexico City,Korea,1,1,Bulgaria,,...,1,AL SHANAR Fallaj Khuzam (KSA),IGNA Ioan (ROU),BUTENKO Valeri (RUS),308,460,NSK,BUL,2,1
386,1986,10 Jun 1986 - 12:00,Group A,Cuauhtemoc,Puebla,Korea,2,3,Italy,,...,1,SOCHA David (USA),URREA Joaquin (MEX),AL SHARIF Jamal (SYR),308,643,NSK,ITA,5,1
434,1990,17 Jun 1990 - 21:00,Group E,Dacia Arena,Udine,Korea,1,3,Spain,,...,1,JACOME GUERRERO Elias V. (ECU),MAGNI Pierluigi (ITA),LOUSTAU Juan (ARG),322,175,NSK,ESP,4,2
444,1990,21 Jun 1990 - 17:00,Group E,Friuli,Udine,Korea,0,1,Uruguay,,...,0,LANESE Tullio (ITA),DIRAMBA Jean Fidele (GAB),JOUINI Neji (TUN),322,290,NSK,URU,1,0
480,1994,23 Jun 1994 - 19:30,Group C,Foxboro Stadium,Boston,Korea,0,0,Bolivia,,...,0,MOTTRAM Leslie (SCO),MATTHYS Luc (BEL),EVERSTIG Mikael (SWE),337,3065,NSK,BOL,0,0
524,1998,13 Jun 1998 - 17:30,Group E,Stade de Gerland,Lyon,Korea,1,3,Mexico,,...,0,BENKO Gunter (AUT),FRED Lencie (VAN),SCHNEIDER Erich (GER),1014,8732,NSK,MEX,4,1
593,2002,04 Jun 2002 - 20:30,Group D,Busan Asiad Main Stadium,Busan,Korea,2,0,Poland,,...,0,RUIZ Oscar (COL),DORIRI Elise (VAN),LINDBERG Leif (SWE),43950100,43950014,NSK,POL,2,1
609,2002,10 Jun 2002 - 15:30,Group D,Daegu World Cup Stadium,Daegu,Korea,1,1,USA,,...,1,MEIER Urs (SUI),BEREUTER Egon (AUT),TOMUSANGE Ali (UGA),43950100,43950030,NSK,USA,2,1
635,2002,18 Jun 2002 - 20:30,Round of 16,Daejeon World Cup Stadium,Daejeon,Korea,2,1,Italy,Win on Golden Goal,...,0,MORENO Byron (ECU),RATTALINO Jorge (ARG),SZEKELY Ferenc (HUN),43950200,43950056,NSK,ITA,3,0
642,2002,29 Jun 2002 - 20:00,Third place,Daegu World Cup Stadium,Daegu,Korea,2,3,Turkey,,...,3,MANE Saad (KUW),ALTRAIFI Ali (KSA),VERGARA Hector (CAN),43950500,43950063,NSK,TUR,5,4
655,2006,13 Jun 2006 - 15:00,Group G,"FIFA World Cup Stadium, Frankfurt",Frankfurt/Main,Korea,2,1,Togo,,...,1,POLL Graham (ENG),SHARP Philip (ENG),TURNER Glenn (ENG),97410100,97410014,NSK,TOG,3,1
710,2010,12 Jun 2010 - 13:30,Group B,Port Elizabeth Stadium,Nelson Mandela Bay/Port Elizabeth,Korea,2,0,Greece,,...,0,HESTER Michael (NZL),HINTZ Jan Hendrik (NZL),MAKASINI Tevita (TGA),249722,300061459,NSK,GRE,2,1
753,2010,25 Jun 2010 - 16:00,Group G,Mbombela Stadium,Nelspruit,Korea,0,3,C�te d'Ivoire,,...,2,Alberto UNDIANO MALLENCO (ESP),MARTINEZ Fermin (ESP),YUSTE Juan (ESP),249722,300061486,NSK,CIV,3,2
802,2014,22 Jun 2014 - 16:00,Group H,Estadio Beira-Rio,Porto Alegre,Korea,2,4,Algeria,,...,3,ROLDAN Wilmar (COL),DIAZ Eduardo (COL),LESCANO Christian (ECU),255931,300186495,NSK,ALG,6,3
818,2014,26 Jun 2014 - 17:00,Group H,Arena de Sao Paulo,Sao Paulo,Korea,0,1,Belgium,,...,0,Ben WILLIAMS (AUS),CREAM Matthew (AUS),ANAZ Hakan (AUS),255931,300186480,NSK,BEL,1,0

In [22]:
df.loc[df["Away Team Name"].str.contains('Korea')]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,...,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials,Total Goals,Half-time Goals
80,1954,17 Jun 1954 - 18:00,Group 2,Hardturm,Zurich,Hungary,9,0,Korea,,...,0,VINCENTI Raymond (FRA),VON GUNTER Albert (SUI),STEINER Carl (AUT),211,1294,HUN,NSK,9,4
88,1954,20 Jun 1954 - 17:00,Group 2,Charmilles,Geneva,Turkey,7,0,Korea,,...,0,MARINO Esteban (URU),ORLANDINI Vincenzo (ITA),SCHONHOLZER Ernest (SUI),211,1304,TUR,NSK,7,4
171,1966,12 Jul 1966 - 19:30,Group 4,Ayresome Park,Middlesbrough,Soviet Union,3,0,Korea,,...,0,GARDEAZABAL Juan (ESP),KANDIL Aly Hussein (EGY),DIENST Gottfried (SUI),238,1710,URS,NSK,3,2
195,1966,23 Jul 1966 - 15:00,Quarter-finals,Goodison Park,Liverpool,Portugal,5,3,Korea,,...,3,ASHKENAZI Menachem (ISR),GALBA Karol (TCH),SCHWINTE Pierre (FRA),239,1702,POR,NSK,8,5
364,1986,02 Jun 1986 - 12:00,Group A,Estadio Ol�mpico Universitario,Mexico City,Argentina,3,1,Korea,,...,0,SANCHEZ ARMINIO Victoriano (ESP),GONZALEZ ROA Gabriel (PAR),DIAZ PALACIO Jesus (COL),308,395,ARG,NSK,4,2
421,1990,12 Jun 1990 - 17:00,Group E,Marc Antonio Bentegodi,Verona,Belgium,2,0,Korea,,...,0,MAURO Vincent (USA),SNODDY Alan (NIR),COURTNEY George (ENG),322,57,BEL,NSK,2,0
464,1994,17 Jun 1994 - 19:30,Group C,Cotton Bowl,Dallas,Spain,2,2,Korea,,...,0,MIKKELSEN Peter (DEN),CHRISTENSEN Carl-Johan Meyer (DEN),PEARSON Roy (ENG),337,3050,ESP,NSK,4,0
490,1994,27 Jun 1994 - 16:00,Group C,Cotton Bowl,Dallas,Germany,3,2,Korea,,...,0,QUINIOU Joel (FRA),IVANOV Valentin (RUS),HASSAN Abdel-Magid (EGY),337,3076,GER,NSK,5,3
542,1998,20 Jun 1998 - 21:00,Group E,Stade V�lodrome,Marseilles,Netherlands,5,0,Korea,,...,0,WOJCIK Ryszard (POL),POCIEGIEL Jacek (POL),DUPANOV Yuri (BLR),1014,8749,NED,NSK,5,2
556,1998,25 Jun 1998 - 16:00,Group E,Parc des Princes,Paris,Belgium,1,1,Korea,,...,0,REZENDE Marcio (BRA),PINTO Arnaldo (BRA),ARANGO Jorge Luis (COL),1014,8765,BEL,NSK,2,1
625,2002,14 Jun 2002 - 20:30,Group D,Incheon Football Stadium,Incheon,Portugal,0,1,Korea,,...,0,SANCHEZ Angel (ARG),ALTRAIFI Ali (KSA),SZEKELY Ferenc (HUN),43950100,43950047,POR,NSK,1,0
639,2002,22 Jun 2002 - 15:30,Quarter-finals,Gwangju World Cup Stadium,Gwangju,Spain,0,0,Korea,Korea Republic win on penalties (3 - 5),...,0,EL GHANDOUR Gamal (EGY),TOMUSANGE Ali (UGA),RAGOONATH Michael (TRI),43950300,43950059,ESP,NSK,0,0
640,2002,25 Jun 2002 - 20:30,Semi-finals,Seoul World Cup Stadium,Seoul,Germany,1,0,Korea,,...,0,MEIER Urs (SUI),ARNAULT Frederic (FRA),AMLER Evzen (CZE),43950400,43950061,GER,NSK,1,0
672,2006,18 Jun 2006 - 21:00,Group G,Zentralstadion,Leipzig,France,1,1,Korea,,...,0,ARCHUNDIA Benito (MEX),RAMIREZ Jose (MEX),VERGARA Hector (CAN),97410100,97410029,FRA,NSK,2,1
691,2006,23 Jun 2006 - 21:00,Group G,"FIFA World Cup Stadium, Hanover",Hanover,Switzerland,2,0,Korea,,...,0,ELIZONDO Horacio (ARG),GARCIA Dario (ARG),OTERO Rodolfo (ARG),97410100,97410046,SUI,NSK,2,1
721,2010,15 Jun 2010 - 20:30,Group G,Ellis Park Stadium,Johannesburg,Brazil,2,1,Korea,,...,0,KASSAI Viktor (HUN),EROS Gabor (HUN),VAMOS Tibor (HUN),249722,300061490,BRA,NSK,3,0
725,2010,17 Jun 2010 - 13:30,Group B,Soccer City Stadium,Johannesburg,Argentina,4,1,Korea,,...,1,DE BLEECKERE Frank (BEL),HERMANS Peter (BEL),VROMANS Walter (BEL),249722,300061458,ARG,NSK,5,3
737,2010,21 Jun 2010 - 13:30,Group G,Cape Town Stadium,Cape Town,Portugal,7,0,Korea,,...,0,POZO Pablo (CHI),BASUALTO Patricio (CHI),MONDRIA Francisco (CHI),249722,300061487,POR,NSK,7,1
742,2010,22 Jun 2010 - 20:30,Group B,Durban Stadium,Durban,Nigeria,2,2,Korea,,...,1,Oleg�rio BENQUEREN�A (POR),CARDINAL Jose (POR),MIRANDA Bertino (POR),249722,300111115,NGA,NSK,4,2
756,2010,26 Jun 2010 - 16:00,Round of 16,Port Elizabeth Stadium,Nelson Mandela Bay/Port Elizabeth,Uruguay,2,1,Korea,,...,0,Wolfgang STARK (GER),SALVER Jan-Hendrik (GER),PICKEL Mike (GER),249717,300061504,URU,NSK,3,1
788,2014,17 Jun 2014 - 18:00,Group H,Arena Pantanal,Cuiaba,Russia,1,1,Korea,,...,0,PITANA Nestor (ARG),MAIDANA Hernan (ARG),BELATTI Juan Pablo (ARG),255931,300186499,RUS,NSK,2,0

## Summary

In this lab, you learned how to access data within Pandas!